name: Build test
on:
  push:
    branches:
      - master_good
jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: bash ci.sh deps
    - name: Build LLVM
      run: bash build-toolchain.sh
